language: node_js
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
node_js:
    - "4"
    - "6"
    - "7"
before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
