// Generated by CoffeeScript 1.6.1

(function(root, factory) {
  if (typeof exports === 'object') {
    return module.exports = factory();
  } else if (typeof define === 'function' && define.amd) {
    return define(factory);
  } else {
    return root.Queue = factory();
  }
})(this, function() {
  'use strict';
  var Queue;
  return Queue = function() {
    var dequeue, enqueue, first, last, length, peek, q;
    first = 0;
    last = -1;
    q = [];
    enqueue = function(val) {
      return q[++last] = val;
    };
    dequeue = function() {
      var val;
      if (first > last) {
        return void 0;
      }
      val = q[first];
      delete q[first];
      first++;
      return val;
    };
    length = function() {
      return last - first + 1;
    };
    peek = function() {
      if (first > last) {
        return void 0;
      }
      return q[first];
    };
    return {
      enqueue: enqueue,
      dequeue: dequeue,
      length: length,
      peek: peek
    };
  };
});
